[package]
name = "csv-clean"
version = "0.1.0"
authors = ["Mike Clarke <mike@lambdafunctions.com>"]

[dependencies]
csv = "1"
serde_json = "1.0"
chrono = "0.4"

[dependencies.clap]
version = "2.32.0"
default-features = false
features = ["wrap_help", "yaml"]
